name: Issue created

on: issues

jobs:
  issue-created:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.event.issue.title, 'new project: ')
    steps:
    - uses: actions/checkout@v2
    - name: Extract location and project
      run: |
        location=$(echo "$GITHUB_EVENT_PATH" | grep -oE 'location: (.*)' | cut -d ' ' -f 2)
        project=$(echo "$GITHUB_EVENT_PATH" | grep -oE 'project: (.*)' | cut -d ' ' -f 2)
    - name: Check for folder
      run: |
        if [ ! -d "$location" ]; then
          echo "The specified folder does not exist."
          exit 1
        fi
    - name: Check for valid project URL
      run: |
        project_url=$(echo "$project" | sed -E 's|(https?://)?(www.)?(.+)/(.+)|\3/\4|')
        project_exists=$(curl -s -o /dev/null -w "%{http_code}" "https://api.github.com/repos/$project_url")
        if [ "$project_exists" != "200" ]; then
          echo "The specified project URL is not valid."
          exit 1
        fi
    - name: Close issue
      if: failure()
      uses: peter-evans/close-issue@v2
      with:
        issue-title: 'The specified folder or project URL is not valid.'
        issue-body: |
          The folder specified in the `location` field of the issue or the URL provided in the `project` field is not valid. Please provide valid values and try again.
        labels: invalid
