name: report generator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  report-generator:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with: 
          submodules: true
      - name: run report generator
        run: |
          python3 report.py ${{ secrets.GITHUB_TOKEN }}
      - name: save changes
        run: |
          git config --global user.email "theta-bot@users.noreply.github.com"
          git config --global user.name "theta-bot"
          git commit --all --message "𝚌𝚛𝚘𝚗𝚋𝚘𝚝" || echo "no changes to commit"
          git push
