name: Update Submodules

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  submodule-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update Submodules
        run: |
          git config --global user.email "githubintegration@theta.co.nz"
          git config --global user.name "theta-bot"
          git submodule update --init --recursive --remote
          git commit --all --message "submodule-autoupdate" || echo "no changes to commit"
          git push
